export const initialState = {
  vehicleOf: {
    VIN: "",
    accelerationTime: "",
    arrisCode: "",
    bodyType: "",
    carLocation: "",
    driveWheelConfiguration: "",
    exteriorColor: "",
    firstRegisteredDate: "",
    interiorColor: "",
    knownDamage: "",
    make: "",
    mileage: "",
    model: "",
    roofLoad: "",
    seatingCapacity: "",
    steeringPosition: "",
    value: "",
    verifiedOwner: "",
    year: "",
    ownerOf: "",
    index: "",
  },
  isLoading: false,
  error: null,
};
